listen_http: ":8003"
static_path: "frontend/dist"
empty_max_age: 5m
order:
  - US-West
  - US-East
  - EU-Central

servers:
  - host: us1.uncledane.com
    port: 27015
    pass: xx
    region: US West
    country_code: us
    default_map: pl_badwater_pro_v12

  - host: us3.uncledane.com
    port: 27015
    pass: xx
    region: US West
    country_code: us
    default_map: pl_upward

  - host: us2.uncledane.com
    port: 27015
    pass: xx
    region: US East
    country_code: us
    default_map: pl_upward

  - host: eu1.uncledane.com
    port: 27015
    pass: xx
    region: EU Central
    country_code: de
    default_map: pl_badwater_pro_v12

  - host: eu2.uncledane.com
    port: 27015
    pass: xx
    region: EU Central
    country_code: de
    default_map: pl_upward